name: C++ Build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  release:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install C++ compilers
        run: |
          sudo apt update
          sudo apt install -y g++
      - name: Check for C++ files
        id: check_cpp_files
        run: |
          if [ -z "$(find . -name '*.cpp')" ]; then
            echo "No C++ files found"
            echo "${{ format('{0}={1}', 'cpp_files', 'false') }}" >> $GITHUB_STATE
          else
            echo "${{ format('{0}={1}', 'cpp_files', 'true') }}" >> $GITHUB_STATE
          fi
      - name: Compile C++ code (C++14)
        if: steps.check_cpp_files.outputs.cpp_files == 'true'
        run: g++ -std=c++14 -Wall -Wextra -Werror -pedantic -c *.cpp
      - name: Compile C++ code (C++17)
        if: steps.check_cpp_files.outputs.cpp_files == 'true'
        run: g++ -std=c++17 -Wall -Wextra -Werror -pedantic -c *.cpp
      - name: Compile C++ code (C++20)
        if: steps.check_cpp_files.outputs.cpp_files == 'true'
        run: g++ -std=c++20 -Wall -Wextra -Werror -pedantic -c *.cpp
      - name: Compile C++ code (C++23)
        if: steps.check_cpp_files.outputs.cpp_files == 'true'
        run: g++ -std=c++23 -Wall -Wextra -Werror -pedantic -c *.cpp
      - name: Upload build artifact
        if: steps.check_cpp_files.outputs.cpp_files == 'true' && success()
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: .
